export const FETCH_API_TASK = "FETCH_API_TASK";
export const FETCH_API_TASK_SUCCESS = "FETCH_API_TASK_SUCCESS";
export const FETCH_API_TASK_ERR = "FETCH_API_TASK_ERR";

export const FETCH_API_TASK_WHEN_CHANGE_LENGTH =
  "FETCH_API_TASK_WHEN_CHANGE_LENGTH";
export const FETCH_API_TASK_WHEN_CHANGE_LENGTH_SUCCESS =
  "FETCH_API_TASK_WHEN_CHANGE_LENGTH_SUCCESS";
export const FETCH_API_TASK_WHEN_CHANGE_LENGTH_ERR =
  "FETCH_API_TASK_WHEN_CHANGE_LENGTH_ERR";

export const POST_API_TASK = "POST_API_TASK";
export const POST_API_TASK_SUCCESS = "POST_API_TASK_SUCCESS";
export const POST_API_TASK_ERR = "POST_API_TASK_ERR";

export const DELETE_API_TASK = "DELETE_API_TASK";
export const DELETE_API_TASK_SUCCESS = "DELETE_API_TASK_SUCCESS";
export const DELETE_API_TASK_ERR = "DELETE_API_TASK_ERR";

export const UPDATE_API_TASK = "UPDATE_API_TASK";
export const UPDATE_API_TASK_SUCCESS = "UPDATE_API_TASK_SUCCESS";
export const UPDATE_API_TASK_ERR = "UPDATE_API_TASK_ERR";

export const UPDATE_API_TASK_STATUS = "UPDATE_API_TASK_STATUS";
export const UPDATE_API_TASK_STATUS_SUCCESS = "UPDATE_API_TASK_STATUS_SUCCESS";
export const UPDATE_API_TASK_STATUS_ERR = "UPDATE_API_TASK_STATUS_ERR";
